export type Product = {
  id: number;
  slug: string;
  name: string;
  category: string;
  price: string;
  recent?: boolean;
  image: string;
  imageAlt: string;
  cardDescription: string;
  shortDescription: string;
  description: string[];
  features: string[];
};

export const products: Product[] = [
  {
    id: 1,
    slug: "whole-home-filtration-system",
    name: "Whole Home Filtration System",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: true,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778746945/ChatGPT_Image_May_14_2026_01_41_26_PM_bxdovi.webp",
    imageAlt: "Whole Home Filtration System",
    cardDescription: "Whole Home Micron Water Filtration System",
    shortDescription: "A powerful point-of-entry filtration system using gradient density sediment filtration & Activated Carbon Fibre technology to protect every tap in your home.",
    description: [
      "The Gen 3 Hello Water Whole Home Filtration System delivers powerful point-of-entry filtration using advanced multi-stage cartridge technology. Built to purify the water flowing throughout your entire large home, or small aged care facility or boutique hotel it combines gradient density sediment filtration, Activated Carbon Fibre (ACF) technology, & Diamond Flow dual-technology filtration to aggressively target both physical & chemical contaminants.",
      "DGD Series cartridges (0.5 micron nominal), made from 100% pure polypropylene, capture sand, silt, rust, clay & micro-plastics with high efficiency. Their gradient density design filters larger particles first, then finer contaminants deeper within the cartridge, maximising dirt-holding capacity, maintaining strong flow, & extending filter life.",
      "At its core is the EnnoPure ePureFlo ACF cartridge, engineered for advanced chemical filtration. It reduces chlorine taste & odour by 200% compared to regular cartridges, while also targeting up to 99.99% PFAS, VOCs & other chemical contaminants. By combining sediment filtration & carbon block performance in one media, it delivers high adsorption without releasing carbon fines.",
      "The Pentair DFX Series Diamond Flow cartridge adds an additional dual-technology filtration layer, combining a polyspun sediment exterior with a high-performance carbon block core. Designed for superior particulate reduction & resistance to premature clogging, it aggressively reduces chlorine taste, odour, sediment, rust, silt, & fine debris while maintaining low pressure drop & consistent high-flow performance.",
      "The cartridges are tested against NSF/ANSI 42, 53 & 401 standards, covering aesthetic effects such as chlorine taste & odour, health-related contaminant reduction including heavy metals, & emerging compounds such as pharmaceuticals, pesticides & trace organic contaminants, ensuring comprehensive water quality performance across multiple contaminant categories.",
      "Housed in a marine-grade stainless steel cabinet with a rugged, high-performance design, the system is built for durability in harsh conditions. A patented ventilation system prevents heat build-up, while a built-in bypass line & pressure adjustment valve provide flexibility, control & consistent performance.",
      "With a peak flow rate of up to 119 litres per minute, it is ideal for larger homes & semi commercial applications requiring high-volume, reliable water supply.",
    ],
    features: [
      "Advanced multi-stage whole home filtration",
      "Dual-gradient sediment filtration (0.5 micron nominal)",
      "Proprietary ACF (Activated Carbon Fibre) technology",
      "PFAS Certified EnnoPure Water Technology, VOC & chemical contaminant reduction",
      "Reduces fluoride, lead, mercury, manganese, other heavy metals & scale forming minerals",
      "Bacteriostatic filter media",
      "Marine-grade stainless steel cabinet",
      "SS316 bracket with polished mirror finish",
      "Patented ventilation system for excessive heat prevention",
      "Built-in bypass system hidden inside the cabinet for sleek look and convenience",
      "Integrated bronze pressure adjustment valve",
      "Large dialed stainless steel Pressure gauges for better pressure reading",
      "20\" high-capacity filter housings with double buna O-ring sealing",
      "NSF/ANSI 42 & WaterMark certified components",
      "Ideal for large residential & semi-commercial applications",
      "Up to 119L/min high-flow capacity at peak demand",
    ],
  },
  {
    id: 2,
    slug: "pentair-green-reverse-osmosis-system",
    name: "PENTAIR GREEN REVERSE OSMOSIS SYSTEM",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: true,
    image: "",
    imageAlt: "Pentair Green Reverse Osmosis System",
    cardDescription: "Premium 4-Stage Reverse Osmosis Purification",
    shortDescription: "A premium 4-stage under-sink purification solution powered by Pentair GRO technology, delivering pure water with up to 96.8% TDS reduction.",
    description: [
      "Experience cleaner, fresher, better-tasting water with the Hello Water Reverse Osmosis System; a premium 4-stage purification solution engineered to deliver high-quality drinking water directly from your kitchen tap.",
      "Powered by advanced Pentair GRO reverse osmosis technology, this compact under-sink system targets dissolved salts, minerals, chlorine taste, odours, sediment, cysts, & microscopic impurities to produce exceptionally pure water with up to 96.8% TDS reduction performance.",
      "Stage 1 utilizes advanced 5-micron sediment filtration to capture sand, silt, rust, dirt, & suspended particles before they enter the system, helping protect both the filtration components & household plumbing.",
      "Stage 2 features a high-performance carbon block pre-filter designed to reduce chlorine taste, unwanted odours, & chemical impurities while significantly improving the overall taste & freshness of your water.",
      "Stage 3 incorporates Pentair’s innovative high recovery GRO reverse osmosis membrane technology, engineered to reduce dissolved solids, salts, minerals, cysts, & microscopic contaminants while operating more efficiently than conventional reverse osmosis systems.",
      "Stage 4 uses a premium carbon polishing filter to provide a final layer of taste enhancement, delivering crisp, refreshing drinking water on demand.",
      "Designed with a compact under-sink footprint, integrated storage tank, & dedicated drinking water faucet, the system provides purified water instantly for drinking, cooking, tea, coffee, & refrigerator ice makers — delivering cleaner water with reliable everyday convenience.",
    ],
    features: [
      "Advanced 4-stage reverse osmosis purification",
      "Pentair high recovery GRO membrane technology",
      "Up to 96.8% TDS reduction performance",
      "Reduces chlorine taste, odours, dissolved salts & minerals",
      "Certified cyst reduction including Cryptosporidium & Giardia",
      "High-efficiency membrane with improved water recovery",
      "Compact under-sink installation",
      "Integrated storage tank for water on demand",
      "Premium carbon polishing filter",
      "High-flow 3/8\" dispensing line",
      "Simplified encapsulated membrane replacement",
      "NSF/ANSI 58 certified performance",
    ],
  },
  {
    id: 3,
    slug: "everpure-full-flow-micro-filtration-system",
    name: "Everpure Full Flow Micro-Filtration System",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: true,
    image: "",
    imageAlt: "Everpure Full Flow Micro-Filtration System",
    cardDescription: "Commercial-Grade Under-Sink Microfiltration",
    shortDescription: "A powerful commercial-grade under-sink system using Everpure Fibredyne II® technology to deliver high-flow filtered water directly from your existing tap.",
    description: [
      "The Hello Water Everpure Full Flow Micro-Filtration System delivers powerful commercial-grade microfiltration through a compact under-sink design, providing cleaner, fresher, better-tasting water directly from your existing kitchen tap — without the need for a separate faucet.",
      "Powered by advanced Everpure Fibredyne II® filtration technology, this commercial-grade system combines powerful microfiltration with architecturally flow performance to reduce sediment, chlorine taste & odour, chloramine, lead, cysts, & microscopic impurities down to 0.5 micron while maintaining strong, consistent water pressure.",
      "The advanced Fibredyne II® media utilizes high-capacity filtration technology to capture fine particles, dirt, rust, sediment, & contaminants as small as 0.2–0.5 micron, delivering cleaner, clearer water for drinking, cooking, tea, coffee, & everyday use.",
      "Engineered for superior chemical reduction, the system significantly improves water taste & freshness by reducing chlorine taste, odours, chloramine, & other unwanted substances commonly found in municipal water supplies.",
      "Certified to NSF/ANSI Standard 53, the Everpure 4FC also reduces cysts such as Cryptosporidium & Giardia by mechanical means while reducing lead to below EPA standards for safer, healthier drinking water.",
      "Designed for convenience, the compact under-sink system connects directly to your existing cold-water tap; eliminating the need for additional bench holes or separate designer faucets. Its high-flow performance delivers fast, full-pressure filtered water on demand while helping reduce limescale buildup in appliances.",
      "Compact, powerful, & engineered for everyday performance — premium filtered water has never been this simple.",
    ],
    features: [
      "Commercial-grade full-flow microfiltration",
      "Advanced Everpure Fibredyne II® technology",
      "Reduces particles down to 0.5 micron",
      "Reduces chlorine taste, odour & chloramine",
      "Lead reduction to below EPA standards",
      "Certified cyst reduction including Cryptosporidium & Giardia",
      "High-flow filtration with low pressure drop",
      "Helps reduce limescale buildup",
      "Connects directly to existing cold-water tap",
      "No additional faucet required",
      "Compact under-sink installation",
      "NSF/ANSI 53 certified performance",
    ],
  },
  {
    id: 4,
    slug: "2-stage-whole-home-filtration-system",
    name: "2 Stage Whole Home Filtration System",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: true,
    image: "",
    imageAlt: "2 Stage Whole Home Filtration System",
    cardDescription: "Dual-Stage Whole Home Water Filtration",
    shortDescription: "A dual-stage whole home system using Pentek DFX Diamond Flow technology to protect every tap and appliance in your home.",
    description: [
      "Powerful whole-home water filtration built with trusted Pentair technology to deliver cleaner, fresher water to every tap, shower, & appliance throughout your home.",
      "Featuring advanced Pentek DFX Diamond Flow cartridges, this dual-stage system combines 10-micron outer sediment filtration with 1-micron inner carbon block technology to reduce sediment, rust, mud, silt, chlorine taste & odour, chloramine, VOCs, & other common water impurities.",
      "Designed for modern family homes, it delivers a high flow rate of up to 65LPM with low pressure drop, helping maintain strong water pressure while protecting plumbing, fixtures, & appliances from build-up.",
    ],
    features: [
      "Advanced 2-stage whole home water filtration system",
      "Pentek DFX Series Diamond Flow technology",
      "Dual sediment & carbon block filtration in one cartridge",
      "Reduces chlorine taste, odour, & chloramine",
      "Helps reduce sediment, rust, dirt, mud, & silt",
      "Targets volatile organic compounds (VOCs) & chemical impurities",
      "High flow design up to 65 LPM",
      "Low pressure drop for consistent performance",
      "High dirt-holding capacity for longer cartridge life",
      "Helps protect plumbing, fixtures, & appliances",
      "Compact, whole-home cartridge-based system",
      "NSF/ANSI 42 certified components",
      "AS/NZS 4020 & WaterMark certified components",
    ],
  },
  {
    id: 5,
    slug: "the-bottle-water-plant-whole-house-micro-filtration",
    name: "The Whole House Bottle Water Plant",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: false,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778747185/IMG_0215_mjytb4.webp",
    imageAlt: "The Whole House Bottle Water Plant",
    cardDescription: "Whole House Micron Water Filtration",
    shortDescription: "A comprehensive 5-level purification system that treats water at its entry point, providing bottled-quality water from every tap in your home for drinking, bathing, & laundry.",
    description: [
      "The Hello Water Whole Home Purification System uses an advanced 5-level, 3-stage process to treat water at the point it enters your home, ensuring every tap provides clean, filtered water for drinking, bathing, & laundry.",
      "Stage 1 utilizes powerful dual-gradient sediment filtration technology (0.5 micron nominal) to capture sand, silt, rust & organic material, preventing physical contaminants from entering your plumbing & extending the life of downstream filters.",
      "Stage 2 features high-capacity granular activated coconut shell carbon to target chemical contaminants, including chlorine, chloramine, PFAS, pesticides, & industrial solvents, significantly improving the taste, smell, & overall safety of your water.",
      "Stage 3 employs a powerful combination of KDF-55 redox media & coconut shell carbon to reduce heavy metals (lead, mercury, copper), KDF-F for fluoride, while inhibiting bacterial growth (Bacteriostatic) & reducing scale buildup.",
      "Designed  with a peak flow rate of up to 75 litres per minute, this system is ideal for medium-to-large homes, providing a sustainable & cost-effective, eco-friendly alternative to bottled water, Shower and home use.",
    ],
    features: [
      "5-level, 3-stage purification",
      "Dual-gradient sediment filtration (0.5 micron)",
      "Redox (KDF 55 media) technology",
      "Heavy metal & fluoride reduction",
      "Scale inhibition & appliance protection",
      "75L/min high-flow capacity",
      "NSF/ANSI 42, AS/NZS 4020 & WaterMark certified components",
    ],
  },
  {
    id: 6,
    slug: "uv-radiation-micro-filtration-system",
    name: "UV Water Treatment & Micro Filtration System",
    category: "Filtration Systems",
    price: "Call for Price",
    recent: false,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778746943/ChatGPT_Image_May_14_2026_01_46_05_PM_evfc8c.webp",
    imageAlt: "UV Radiation Micro Filtration System all-in-one unit",
    cardDescription: "UV Water Purification System",
    shortDescription: "An advanced all-in-one sterilization system that uses high-performance ultraviolet technology to eliminate 99.9999% of bacteria, combined with multi-stage filtration for pure, chemical-free water.",
    description: [
      "The Pentair®/Pentek® UV Micro Filtration System is a complete whole-house solution that combines advanced multi-stage filtration with high-performance ultraviolet sterilization for pure, safe water.",
      "The core UV technology is tested to eliminate 99.9999% of harmful bacteria, such as E. coli, using a natural, chemical-free purification process that is safe for your family & the environment.",
      "Integrated filtration reduces sediment, dirt, rust, & chlorine, ensuring crystal-clear & better-tasting water for drinking, cooking, & showering throughout your entire home.",
      "Built with durable, commercial-grade components, the system is suitable for mains, rain, & surface water applications, with versatile indoor or outdoor installation options.",
      "Includes a convenient UV lamp countdown timer & performance alarm to ensure the system consistently operates at peak efficiency, providing complete peace of mind.",
    ],
    features: [
      "99.9999% E. coli & bacteria removal",
      "Chemical-free UV purification",
      "Whole-house multi-stage filtration",
      "1 Micron filtration rating",
      "UV lamp timer & performance alarm",
      "Suitable for mains & rainwater",
      "NSF, SGS, AS/NZS 4020 & WaterMark certified components",
    ],
  },
  {
    id: 7,
    slug: "ennopure-epureflo-acf-series-cartridge",
    name: "EnnoPure ePureFlo ACF Series",
    category: "Cartridges",
    price: "$156.00 + GST",
    recent: true,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778744897/IMG_0214_zzup4c.webp",
    imageAlt: "EnnoPure ePureFlo ACF Series Cartridge for advanced chemical filtration",
    cardDescription: "Advanced Activated Carbon Fibre technology. Up to 200% Chlorine reduction.",
    shortDescription: "Advanced proprietary activated carbon fibre technology specifically engineered to deliver up to 200% chlorine reduction, elimination of PFAS & sediment reduction in a single cartridge.",
    description: [
      "EnnoPure ePureFlo ACF Series cartridges are manufactured using advanced proprietary activated carbon fibre technology & are specifically engineered to deliver up to 200% chlorine taste & odour reduction, elimination of PFAS & sediment reduction in a single high-performance filtration cartridge.",
      "Designed for enhanced contaminant removal, these cartridges combine the benefits of traditional carbon block filtration with significantly improved sediment-holding capacity, providing highly efficient dual-purpose filtration for demanding water treatment applications. The advanced ACF media structure delivers exceptional chlorine taste & odour reduction while also effectively reducing a wider range of chemical contaminants, including PFAS compounds.",
      "Engineered for performance, this advanced filtration design allows the cartridges to maintain strong flow performance while resisting premature clogging, even in applications with elevated particulate loading. The advanced adsorption media also contributes to the reduction of emerging contaminants, including up to 99.99% PFAS (per- & polyfluoroalkyl substances), delivering a higher level of water quality protection.",
      "The unique moulded block construction combines efficient sediment pre-filtration with high-capacity activated carbon adsorption, maximising contaminant capture throughout the depth of the cartridge. In addition, a specially fused post-filtration layer prevents the release of carbon fines into the effluent stream, ensuring cleaner operation & improved water clarity.",
      "Manufactured entirely from FDA-compliant materials, these cartridges are tested against NSF/ANSI Standards 42, 53 & 401, making them a reliable solution for residential, food service, commercial & industrial water filtration systems. With excellent particulate reduction & long operational life, they are an ideal choice for applications requiring advanced water quality improvement.",
    ],
    features: [
      "Advanced proprietary activated carbon fibre technology",
      "Up to 200% better chlorine & chloramine reduction compared to conventional cartridges",
      "High sediment-holding capacity for extended filter life",
      "Effective elimination of PFAS by up to 99.99% & other chemical contaminants",
      "Dual-purpose filtration combining sediment filtration & carbon adsorption",
      "Fused post-filtration layer minimises carbon fines release",
      "Nominal 5–10 micron filtration rating",
      "Maintains strong flow performance while resisting premature clogging",
      "Manufactured from FDA-compliant materials",
      "Tested against NSF/ANSI Standards 42, 53 & 401",
      "Suitable for residential, commercial, food service & industrial applications",
    ],
  },
  {
    id: 8,
    slug: "micron-replacement-cartridge",
    name: "Pentek DGD Series",
    category: "Cartridges",
    price: "$49.00 + GST",
    recent: false,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778737849/IMG_0202_chrfcu.webp",
    imageAlt: "Micron Replacement Cartridge Dual for sediment reduction",
    cardDescription: "For Sediment Reduction",
    shortDescription: "A high-capacity sediment reduction cartridge made from 100% pure polypropylene, offering up to three times the dirt-holding capacity of standard filters to protect your home's plumbing & appliances.",
    description: [
      "DGD Series cartridges are manufactured from 100% pure polypropylene & are specifically designed for use in Pentair®/Pentek® Big Blue filter housings.",
      "Engineered for purity, these cartridges do not impart any taste, odor, or colour to the water being filtered. The polypropylene construction also provides excellent chemical resistance & is naturally resistant to bacterial growth, ensuring reliable & hygienic filtration.",
      "The advanced design of the DGD Series combines efficient pre-filtration with selective final filtration, delivering up to three times the dirt-holding capacity of comparable sediment cartridges. This capacity even exceeds that of traditional spun or string-wound filters of the same size.",
      "A larger cartridge diameter reduces the particle load on the filter media, allowing it to operate effectively at higher flow velocities while maintaining strong filtration performance. In addition, the effective filtration depth is increased to 233% of standard cartridges, significantly improving particulate reduction & extending filter life.",
      "Thanks to their robust design & high performance, DGD Series cartridges are an excellent choice for residential, rural & municipal water filtration applications.",
    ],
    features: [
      "Manufactured from pure 100% polypropylene",
      "Spun fibers form a gradient density from outer to inner surfaces",
      "Designed for purity & chemical compatibility",
      "Nominal 0.5, 5, 25 micron ratings",
    ],
  },
  {
    id: 9,
    slug: "pentair-chemical-reduction-cartridges",
    name: "Pentek RFC Series",
    category: "Cartridges",
    price: "$95.00 + GST",
    recent: false,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778737983/IMG_5156_ow9icg_buyqjp.webp",
    imageAlt: "Pentair RFC Series radial flow carbon cartridges",
    cardDescription: "Radial flow carbon cartridges for chemical reduction",
    shortDescription: "Premium radial-flow carbon cartridges designed to significantly reduce chlorine, unpleasant tastes, & odours while maintaining high water pressure, ideal for point-of-entry home filtration.",
    description: [
      "RFC Series cartridges from Pentair®/Pentek® are engineered for reliable, high-performance water filtration. Each cartridge is built with a 70-micron porous polyethylene outer shell & durable polypropylene end-caps, ensuring long-lasting structural integrity & consistent performance.",
      "The 4½-inch diameter cartridge use a spun polypropylene core for added strength in higher-capacity applications. Between the outer shell & the core is a bed of high-quality granular activated carbon (GAC), designed to effectively reduce chlorine, unpleasant tastes, & odours from water.",
      "The RFC Series uses a unique radial flow design, allowing water to pass efficiently through the carbon media. This design delivers the key benefits of GAC filtration -low pressure drop & excellent contaminant reduction- while significantly minimizing the release of carbon fines, which are often associated with traditional GAC cartridges.",
      "RFC Series cartridges are ideal for point-of-entry (POE) filtration systems & other high-flow residential applications where consistent water quality & reliable performance are essential.",
    ],
    features: [
      "Provides effective chlorine taste & odour reduction",
      "Unique design reduces carbon fines in filtered water",
      "Pentek RFC Cartridges are ideal for point-of-entry (POE) & other high flow rate applications",
    ],
  },
  {
    id: 10,
    slug: "pentair-coconut-shell-carbon-cartridges",
    name: "Pentek DBC Series",
    category: "Cartridges",
    price: "$135.00 + GST",
    recent: false,
    image: "https://res.cloudinary.com/dnlb02zp9/image/upload/v1778737848/IMG_0204_txnipz.webp",
    imageAlt: "Pentair Coconut Shell Carbon Cartridges enhanced with KDF",
    cardDescription: "Enhanced with KDF. Minimize heavy metals & chemicals for water filtration",
    shortDescription: "An advanced coconut-shell carbon filter enhanced with KDF-55 media, specifically engineered to reduce heavy metals & harmful chemicals while preventing lime & scale buildup in your pipes.",
    description: [
      "DBC Series cartridges from Pentair®/Pentek® are designed to deliver high-capacity filtration & enhanced protection against scale buildup. Each cartridge is enhanced with KDF 55 media, which helps inhibit the formation of lime & scale buildup that can damage plumbing systems & household appliances.",
      "These cartridges are constructed using high-performance granular activated coconut shell carbon, providing effective reduction of chlorine, chloramine, fluoride, micro-plastics, unpleasant tastes, & odours in water. To further improve filtration performance, they include a 5-micron spun-bonded polypropylene post-sediment element, which increases dirt-holding capacity & captures fine particles.",
      "The combination of advanced carbon filtration & KDF technology makes UDS & DBC Series cartridges ideal for high-capacity applications, particularly in environments where chlorine reduction & scale control are essential for maintaining water quality & protecting equipment.",
    ],
    features: [
      "Bodies are constructed with high grade polypropylene or polystyrene",
      "Spin & sonic welding assembly assures a uniform hermetic seal, which improves overall reliability",
      "Cartridge volumes are some of the highest in the industry",
      "Maximum Pressure: 125 PSI",
    ],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
